# Generated by Django 5.2.1 on 2025-05-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuerdos', '0002_categoria_recuerdo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recuerdo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recuerdos/'),
        ),
        migrations.AlterField(
            model_name='recuerdo',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recuerdo',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recuerdo',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
